#!/usr/bin/env bash
set -e

test_promise() {
  kubectl --context=kind-worker get crds postgresqls.acid.zalan.do
  kubectl --context=kind-worker wait --for=condition=Available --timeout=120s deployment/postgres-operator
}

test_resource_request() {
  kubectl --context=kind-worker wait --for=condition=ready --timeout=300s pod -l spilo-role=master
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
