#!/usr/bin/env bash
set -e

test_promise() {
  kubectl --context=kind-worker get crds postgresqls.acid.zalan.do
  kubectl --context=kind-worker wait --for=create --timeout=120s deployment/postgres-operator
  kubectl --context=kind-worker wait --for=condition=Available --timeout=120s deployment/postgres-operator
}

test_resource_request() {
  echo "Waiting for spilo master pod to be created..."
  until kubectl --context=kind-worker get pod -l spilo-role=master --no-headers 2>/dev/null | grep -q .; do sleep 5; done
  kubectl --context=kind-worker wait --for=condition=ready --timeout=300s pod -l spilo-role=master
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
