---
apiVersion: marketplace.kratix.io/v1alpha1
kind: postgresql
metadata:
  name: dev
  namespace: default
spec:
  env: dev
  teamId: acme-org-team-b
  dbName: bestdb
  backupEnabled: false
---
apiVersion: marketplace.kratix.io/v1alpha1
kind: postgresql
metadata:
  name: testing
  namespace: default
spec:
  env: dev
  teamId: acme-org-team-c
  dbName: bestdb
  backupEnabled: false
