apiVersion: platform.kratix.io/v1alpha1
kind: PromiseRelease
metadata:
  name: postgresql
spec:
  version: v1.0.0-beta.2
  sourceRef:
    type: http
    url: https://raw.githubusercontent.com/syntasso/promise-postgresql/a2bfe298dc23104e18ba955fb216a23ef44f203d/promise.yaml
