#!/usr/bin/env bash

set -ex

PWD="$( cd $(dirname $0)/.. && pwd)"

urls=(
    "https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgresql.crd.yaml"
    "https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/postgresteam.crd.yaml"
    "https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/operatorconfiguration.crd.yaml"
)

mkdir -p $PWD/configure-pipeline/dependencies

for url in "${urls[@]}"; do
    curl -sL -o $PWD/configure-pipeline/dependencies/$(basename $url) $url
done
