#!/usr/bin/env bash

set -eux

PWD="$( cd $(dirname $0)/.. && pwd)"

mkdir -p $PWD/configure-pipeline/resources

instance_urls=(
    "https://raw.githubusercontent.com/zalando/postgres-operator/v1.11.0/manifests/minimal-postgres-manifest.yaml"
)

for url in "${instance_urls[@]}"; do
    curl -sL -o $PWD/configure-pipeline/resources/$(basename $url) $url
done
