#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

set -e

promise_name="postgresql"
pipeline_dir=configure-pipeline
version=v0.1.0
if [ -f ${PWD}/${pipeline_dir}/VERSION ]; then
  version=$(cat ${PWD}/${pipeline_dir}/VERSION)
fi
pipeline_image="ghcr.io/syntasso/promise-${promise_name}/${promise_name}-${pipeline_dir}:${version}"

while [ $# -gt 0 ]; do
  case "$1" in
    build)
      docker build \
        --tag "${pipeline_image}" \
        --platform linux/amd64 \
        "${PWD}/configure-pipeline" ;;

    load)
      kind load docker-image "${pipeline_image}" --name platform ;;

    push)
      docker push "${pipeline_image}" ;;

    rmi)
      docker rmi --force "${pipeline_image}" ;;

    pull)
      docker pull "${pipeline_image}" ;;

    *)
      echo "unknown command $1"
      exit 1
      ;;
  esac
  shift
done
